### ISSUE TITLE
akses ke crud dengan localhost:8000/mahasiswa

### ISSUE THREAD

**Issue by setioryski** [RifkiCS29/laravel-crud#5]
di tutorial gak dikasih tau cara akses ke crudnya
alhasil cuma kelihatan laravel aja

**Comment by RifkiCS29** [comment]
> di tutorial gak dikasih tau cara akses ke crudnya alhasil cuma kelihatan laravel aja

Bisa lihat route nya "/mahasiswa"

**Comment by setioryski** [comment]
bisa tolong dijelaskan apa yang dimaksud rutenya kak ?
lihatnya gimana ya ?
soalnya saya tadi nebak2 mahasiswa

**Comment by RifkiCS29** [comment]
> bisa tolong dijelaskan apa yang dimaksud rutenya kak ? lihatnya gimana ya ? soalnya saya tadi nebak2 mahasiswa

Coba baca dulu dokumentasi laravel

**Comment by setioryski** [comment]
mohon maaf ya kak, apa saya yang kurang mengerti

tapi di dokumentasi tutorialnya
12.Setelah selesai, Jalankan perintah php artisan serve maka dapat diakses dengan http://localhost:8000/
harusnya kan http://localhost:8000/mahasiswa

btw terimakasih banyak kak
akibat projectnya saya jad ngerti laravel

**Comment by RifkiCS29** [comment]
> mohon maaf ya kak, apa saya yang kurang mengerti
> 
> tapi di dokumentasi tutorialnya 12.Setelah selesai, Jalankan perintah php artisan serve maka dapat diakses dengan http://localhost:8000/ harusnya kan http://localhost:8000/mahasiswa
> 
> btw terimakasih banyak kak akibat projectnya saya jad ngerti laravel

Terimakasih koreksi nya
